### ISSUE TITLE
BUG - Certain potion effects do not work

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#13]
Hi there,

Im trying to option effect to classes via the class config file, and the option effects INCREASE_DAMAGE and HEALTH_BOOST generate errors while Speed, GLOWING and JUMP seen ok. 

Here is an example:
```
Tiers:
  1: 
    Potions:
      SPEED 1: 1 hour,
      GLOWING 1: 1 hour,
      JUMP 2: 1 hour,
      INCREASE_DAMAGE 2: 1 hour
```

Here is the error: 
```

[INFO 02/28/2018 21:05:47
21:05:47
Owizardo issued server command: /p reload

21:05:48
*-----------------------------------------------*
Reloading plugin Puncher v1.1.7
*-----------------------------------------------*
Loading arenas (1) ..
 > Loading StarShip
Loading classes (9) ..
 > Loading Creeper
 > Loading DonkeyKong
Puncher 1.1.7 encountered a w! Please check your error.log and report this issue with the information in that file.
*-----------------------------------------------*
 Error loading class from DonkeyKong.yml
*-----------------------------------------------*
[Puncher] Puncher 1.1.7 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
java.lang.RuntimeException: me.kangarko.puncher.nul . .w: Report / In DonkeyKong.yml, please set the INCREASE_DAMAGE 2 potion to format: <potion name> <level>: <duration>
	at me.kangarko.puncher.nul . .com5.super(SourceFile:548)
	at me.kangarko.puncher.nul . .LPT9.try(SourceFile:53)
	at me.kangarko.puncher.nul . .Lpt1.finally(SourceFile:172)
	at me.kangarko.puncher.nul . .Lpt1.new(SourceFile:164)
	at me.kangarko.puncher.nul . .ah.for(SourceFile:421)
	at me.kangarko.puncher.nul . .ah.break(SourceFile:387)
	at me.kangarko.puncher.nul . .Com2.package(SourceFile:20)
	at me.kangarko.puncher.nul . .COM7.short(SourceFile:182)
	at me.kangarko.puncher.nul . .lPt2.onCommand(SourceFile:53)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[Puncher] *-----------------------------------------------*
[Puncher]  Error reloading Puncher 1.1.7
[Puncher] *-----------------------------------------------*
[GameAPI] Successfully hooked into: Puncher v1.1.7](url)
```

**Comment by kangarko** [comment]
Thank you for reporting, I have added them & fixed this.

**Comment by Owizardo** [comment]
Ok great thank you ill give it a try later tonight.
