### ISSUE TITLE
Exception whilst handling conversation input

### ISSUE THREAD

**Issue by mibby** [kangarko/Puncher#20]
Puncher v1.2.4
Paper dev 1427 (Spigot 1.12.2)
```
[05:30:14] [Server thread/WARN]: [Puncher] Plugin Puncher v1.2.4 generated an exception whilst handling conversation input
java.lang.NullPointerException: null
	at java.lang.String.replace(String.java:2142) ~[?:?]
	at me.kangarko.puncher.nul . .CoM6$1.acceptValidatedInput(SourceFile:48) ~[Puncher-1.2.4.jar:?]
	at org.bukkit.conversations.ValidatingPrompt.acceptInput(ValidatingPrompt.java:26) ~[patched_1.12.2.jar:git-Paper-1427]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228) ~[patched_1.12.2.jar:git-Paper-1427]
	at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [patched_1.12.2.jar:git-Paper-1427]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1300) [patched_1.12.2.jar:git-Paper-1427]
	at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1291) [patched_1.12.2.jar:git-Paper-1427]
	at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [patched_1.12.2.jar:git-Paper-1427]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:854) [patched_1.12.2.jar:git-Paper-1427]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1427]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1427]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1427]
	at java.lang.Thread.run(Thread.java:844) [?:?]

``

**Comment by kangarko** [comment]
Confirmed, when setting team's permission. Fixed soon.
